"""Locomotion gating for sensorimotor mismatch trials.

The sensorimotor block is a closed-loop visuomotor paradigm: optic flow is
generated by the animal's own locomotion, and a mismatch event transiently
decouples the two. If the animal is stationary there is no flow to decouple, so
the event is not a stimulus at all. Gating mismatch trials on running is
therefore a validity requirement rather than statistical hygiene, and a trial
qualifies only when the animal was already running *before* the event and still
running *during* it.

Two threshold conventions are deliberately different and both are reported:

- ``block_speed_summary`` counts samples with ``forward > threshold``, matching
  ``scripts/extract_running_statistics.py`` so its running fractions remain
  comparable with the committed ``running-statistics.json``.
- ``qualifying_trials`` admits a trial when both window means are
  ``>= threshold``, because a window mean exactly at the threshold is running.
"""

from __future__ import annotations

from collections.abc import Sequence

import numpy as np

BASELINE_SECONDS = 0.343
"""Pre-event window, matching the sensorimotor baseline rule in neural_responses."""

RUNNING_THRESHOLDS_CM_S: tuple[float, ...] = (1.0, 2.0, 5.0, 10.0)
"""Reported threshold ladder, so the gating choice is auditable."""

DEFAULT_RUNNING_THRESHOLD_CM_S = 5.0
"""Default gate. Stricter than the 1.0 cm/s floor in extract_running_statistics,
which was chosen to describe whether an animal locomoted at all; a paradigm
premised on self-generated optic flow needs a speed that actually produces flow."""

MINIMUM_QUALIFYING_TRIALS = 8
"""Below this many trials in the worst event type, a session is not analysable."""

SENSORIMOTOR_MIN_INTERVAL_SECONDS = 2.0
"""Protocol minimum between consecutive sensorimotor mismatch onsets.

The released data does not honour it: 19 of 140 pairs fall below 2 s.
"""


def forward_speed(velocity: Sequence[float] | np.ndarray) -> np.ndarray:
    """Clip velocity to forward-only speed, the convention used across P3 figures."""
    return np.maximum(np.asarray(velocity, dtype=float), 0.0)


def window_means(
    times: np.ndarray,
    forward: np.ndarray,
    starts: np.ndarray,
    stops: np.ndarray,
) -> tuple[np.ndarray, np.ndarray]:
    """Mean forward speed within each window, plus the sample count behind it.

    Windows with no samples yield NaN rather than zero, so absent coverage is
    never mistaken for a stationary animal.
    """
    times = np.asarray(times, dtype=float)
    forward = np.asarray(forward, dtype=float)
    starts = np.asarray(starts, dtype=float)
    stops = np.asarray(stops, dtype=float)
    if len(times) != len(forward):
        raise ValueError("times and forward must have the same length.")
    if len(starts) != len(stops):
        raise ValueError("starts and stops must have the same length.")

    low = np.searchsorted(times, starts, side="left")
    high = np.searchsorted(times, stops, side="right")
    cumulative = np.concatenate([[0.0], np.cumsum(forward)])
    counts = (high - low).astype(float)
    totals = cumulative[high] - cumulative[low]
    with np.errstate(invalid="ignore", divide="ignore"):
        means = np.where(counts > 0, totals / np.maximum(counts, 1.0), np.nan)
    return means, counts


def qualifying_trials(
    pre_means: np.ndarray,
    event_means: np.ndarray,
    threshold: float,
) -> np.ndarray:
    """Trials where the animal was running in both the baseline and event windows."""
    pre = np.asarray(pre_means, dtype=float)
    event = np.asarray(event_means, dtype=float)
    if len(pre) != len(event):
        raise ValueError("pre_means and event_means must have the same length.")
    with np.errstate(invalid="ignore"):
        gate = (pre >= threshold) & (event >= threshold)
    return np.where(np.isfinite(pre) & np.isfinite(event), gate, False)


def block_speed_summary(forward: np.ndarray, threshold: float) -> dict[str, float]:
    """Block-level forward-speed statistics over the samples inside the block."""
    values = np.asarray(forward, dtype=float)
    values = values[np.isfinite(values)]
    if not values.size:
        raise ValueError("Running series has no finite samples inside the block.")
    return {
        "samples": int(values.size),
        "mean_cm_s": float(np.mean(values)),
        "median_cm_s": float(np.median(values)),
        "p90_cm_s": float(np.percentile(values, 90)),
        # Strict comparison matches extract_running_statistics.py.
        "running_fraction": float(np.mean(values > threshold)),
    }


def summarize_session(
    times: np.ndarray,
    forward: np.ndarray,
    onsets: np.ndarray,
    offsets: np.ndarray,
    labels: Sequence[str],
    *,
    block_window: tuple[float, float] | None = None,
    thresholds: tuple[float, ...] = RUNNING_THRESHOLDS_CM_S,
) -> dict:
    """Summarize one sensorimotor session's locomotion and trial availability.

    ``block_window`` should be the full block span from the stimulus table, so the
    block statistics stay comparable with ``running-statistics.json``. Without it
    the span is inferred from the mismatch events, which excludes the block's
    lead-in and tail and shifts the mean slightly.
    """
    onsets = np.asarray(onsets, dtype=float)
    offsets = np.asarray(offsets, dtype=float)
    if len(labels) != len(onsets):
        raise ValueError("labels and onsets must have the same length.")

    pre_means, pre_counts = window_means(
        times, forward, onsets - BASELINE_SECONDS, onsets
    )
    event_means, event_counts = window_means(times, forward, onsets, offsets)
    label_array = np.asarray(list(labels), dtype="U32")
    unique_labels = sorted(set(label_array.tolist()))

    times_array = np.asarray(times, dtype=float)
    forward_array = np.asarray(forward, dtype=float)
    if block_window is not None:
        block_start, block_stop = float(block_window[0]), float(block_window[1])
    elif len(onsets):
        block_start = float(onsets.min() - BASELINE_SECONDS)
        block_stop = float(offsets.max())
    else:
        block_start, block_stop = -np.inf, np.inf
    inside = (times_array >= block_start) & (times_array <= block_stop)
    block_forward = forward_array[inside]

    summary: dict = {
        "block_window_seconds": [block_start, block_stop],
        "mismatch_trials": int(len(onsets)),
        "labels": unique_labels,
        "minimum_window_samples": int(min(pre_counts.min(), event_counts.min()))
        if len(onsets)
        else 0,
        "trial_pre_mean_cm_s": [round(float(value), 4) for value in pre_means],
        "trial_event_mean_cm_s": [round(float(value), 4) for value in event_means],
        "trial_label": label_array.tolist(),
        "thresholds": {},
    }
    summary["block"] = block_speed_summary(
        block_forward, DEFAULT_RUNNING_THRESHOLD_CM_S
    )
    summary["block_running_fraction_by_threshold"] = {
        f"{threshold:g}": float(np.mean(block_forward > threshold))
        for threshold in thresholds
    }

    for threshold in thresholds:
        gate = qualifying_trials(pre_means, event_means, threshold)
        per_label = {
            label: int(np.sum(gate & (label_array == label))) for label in unique_labels
        }
        minimum = min(per_label.values()) if per_label else 0
        summary["thresholds"][f"{threshold:g}"] = {
            "threshold_cm_s": float(threshold),
            "qualifying_trials": int(gate.sum()),
            "qualifying_fraction": float(gate.mean()) if len(gate) else 0.0,
            "per_label": per_label,
            "minimum_per_label": minimum,
            "available": bool(minimum >= MINIMUM_QUALIFYING_TRIALS),
        }
    return summary


def sensorimotor_trial_masks(
    onsets_by_event: list[np.ndarray],
    offsets_by_event: list[np.ndarray],
    running_times: np.ndarray,
    running_forward: np.ndarray,
) -> tuple[list[np.ndarray], list[dict]]:
    """Which sensorimotor mismatch trials are analysable, per event.

    Two independent requirements. The animal must be running in both the
    pre-event baseline window and the mismatch window, because a closed-loop
    mismatch requires self-generated flow to have been present before it was
    decoupled. And the trial must not follow another mismatch within the
    protocol's intended 2 s minimum, which the released data does not honour.

    The adjacency rule spans **every** mismatch in the block regardless of type,
    because any preceding mismatch leaves the context un-reset. Computing it per
    event type would miss most violations, since trials of one type are far
    apart while different types interleave.
    """
    # Global ordering across all events, so adjacency sees every mismatch.
    flat = [
        (float(onset), event_index, trial_index)
        for event_index, onsets in enumerate(onsets_by_event)
        for trial_index, onset in enumerate(onsets)
    ]
    flat.sort()
    isolated = {(event, trial): True for _onset, event, trial in flat}
    for position in range(1, len(flat)):
        gap = flat[position][0] - flat[position - 1][0]
        if gap < SENSORIMOTOR_MIN_INTERVAL_SECONDS:
            isolated[(flat[position][1], flat[position][2])] = False

    masks: list[np.ndarray] = []
    summaries: list[dict] = []
    for event_index, (onsets, offsets) in enumerate(
        zip(onsets_by_event, offsets_by_event, strict=True)
    ):
        onsets = np.asarray(onsets, dtype=float)
        offsets = np.asarray(offsets, dtype=float)
        pre_mean, _pre_n = window_means(
            running_times,
            running_forward,
            onsets - BASELINE_SECONDS,
            onsets,
        )
        event_mean, _event_n = window_means(
            running_times, running_forward, onsets, offsets
        )
        running = qualifying_trials(
            pre_mean, event_mean, DEFAULT_RUNNING_THRESHOLD_CM_S
        )
        isolated_mask = np.array(
            [isolated[(event_index, trial)] for trial in range(len(onsets))],
            dtype=bool,
        )
        mask = running & isolated_mask
        masks.append(mask)
        summaries.append(
            {
                "runningThresholdCmS": DEFAULT_RUNNING_THRESHOLD_CM_S,
                "minimumIntervalSeconds": SENSORIMOTOR_MIN_INTERVAL_SECONDS,
                "trialsTotal": int(len(onsets)),
                "trialsRunning": int(running.sum()),
                "trialsIsolated": int(isolated_mask.sum()),
                "trialsAnalysable": int(mask.sum()),
                "excludedNotRunning": int((~running).sum()),
                "excludedTooClose": int((~isolated_mask).sum()),
                "meanPreSpeedCmS": round(float(np.nanmean(pre_mean)), 4),
                "meanEventSpeedCmS": round(float(np.nanmean(event_mean)), 4),
            }
        )
    return masks, summaries
